FactoryMM/Controllers/CustOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Providers.Entities;
using FactoryMM.Data;
using FactoryMM.Models.CustomersOrderMm;
using FactoryMM.Models.CustommerMm;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FactoryMM.Controllers
{
    public class CustOrderController : Controller
    {
        private ICustomerOrderRepository _customerOrderRepository;
        private AppDbContext _contex;

        public CustOrderController(ICustomerOrderRepository customerOrderRepository, AppDbContext contex)
        {
            _customerOrderRepository = customerOrderRepository;
            _contex = contex;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            var model = _customerOrderRepository.GetAllCustomerOrder();
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            List<Customer> custNames = new List<Customer>();

            custNames = _contex.Customers.ToList();
            custNames.Insert(0, new Customer { CustId = 0, CustName = "Select" });
            ViewBag.Customer = custNames;
            return View();
        }

        [HttpPost]
        public IActionResult Create(CustomerOrder model)
        {
            if (ModelState.IsValid)
            {
                CustomerOrder newCustomerOrder = new CustomerOrder
                {
                    CustId = model.CustId,
                    ProdInvId = model.ProdInvId,
                    Quantity = model.Quantity,
                    OrderDate = model.OrderDate,
                    DeliveryTakeDate = model.DeliveryTakeDate
                };

                HttpContext.Session.SetString("Test", model.Quantity.ToString());
                _customerOrderRepository.Add(newCustomerOrder);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            CustomerOrder cstomer = _customerOrderRepository.GetCustomerOrder(id);
            CustomerOrder cstomerObj = new CustomerOrder
            {
                CustOrderId = cstomer.CustOrderId,
                CustId = cstomer.CustId,
                ProdInvId = cstomer.ProdInvId,
                Quantity = cstomer.Quantity,
                OrderDate = cstomer.OrderDate,
                DeliveryTakeDate = cstomer.DeliveryTakeDate
            };
            return View(cstomerObj);
        }

        [HttpPost]
        public IActionResult Edit(CustomerOrder model)
        {
            if (ModelState.IsValid)
            {
                CustomerOrder cstomerOrder = _customerOrderRepository.GetCustomerOrder(model.CustOrderId);
                cstomerOrder.CustId = model.CustId;
                cstomerOrder.ProdInvId = model.ProdInvId;
                cstomerOrder.Quantity = model.Quantity;
                cstomerOrder.OrderDate = model.OrderDate;
                cstomerOrder.DeliveryTakeDate = model.DeliveryTakeDate;

                CustomerOrder updateProductInventory = _customerOrderRepository.Update(cstomerOrder);
                return RedirectToAction("Index");
            }
            return View(model);
        }

    }
}

FactoryMM/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FactoryMM.Data;
using FactoryMM.Models.CustommerMm;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FactoryMM.Controllers
{
    public class CustomersController : Controller
    {
        
        private ICustomerRepository _customerRepository;
        private AppDbContext _contex;

        public CustomersController(ICustomerRepository customerRepository, AppDbContext contex)
        {
            _customerRepository = customerRepository;

            _contex = contex;
        }

        public IActionResult Index()
        {
            var model = _customerRepository.GetAllCustomer();
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            
            return View();
        }

        [HttpPost]
        public IActionResult Create(Customer model)
        {
            if (ModelState.IsValid)
            {
                Customer newCustomer = new Customer
                {
                    CustName = model.CustName,
                    Phone = model.Phone,
                    Email = model.Email,
                    OrgName = model.OrgName
                };
                _customerRepository.Add(newCustomer);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Customer cstomer = _customerRepository.GetCustomer(id);
            Customer cstomerObj = new Customer
            {
                CustId = cstomer.CustId,
                CustName = cstomer.CustName,
                Phone = cstomer.Phone,
                Email = cstomer.Email,
                OrgName = cstomer.OrgName,
                Address = cstomer.Address
            };
            return View(cstomerObj);
        }

        [HttpPost]
        public IActionResult Edit(Customer model)
        {
            if (ModelState.IsValid)
            {
                Customer cstomer = _customerRepository.GetCustomer(model.CustId);
                cstomer.CustName = model.CustName;
                cstomer.Phone = model.Phone;
                cstomer.Email = model.Email;
                cstomer.OrgName = model.OrgName;
                cstomer.Address = model.Address;

                Customer updateProductInventory = _customerRepository.Update(cstomer);
                return RedirectToAction("Index");
            }
            return View(model);
        }


    }
}

FactoryMM/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FactoryMM.Data;
using FactoryMM.Models.CustomersOrderMm;
using FactoryMM.Models.SalesMm;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FactoryMM.Controllers
{
    public class SalesController : Controller
    {
        private AppDbContext _context;
        private ISalesRepository _salesRepository;
        private ICustomerOrderRepository _customerOrderRepository;

        public SalesController(ISalesRepository salesRepository, ICustomerOrderRepository customerOrderRepository,AppDbContext context)
        {
            _context = context;
            _salesRepository = salesRepository;
            _customerOrderRepository = customerOrderRepository;


        }

        public IActionResult Index()
        {
            var model = _salesRepository.GetAllSales();
            return View(model);
        }

        [HttpGet]
        public IActionResult Create(int id)
        {
            var qty = _context.CustomerOrders.Find(id).Quantity;
            ViewBag.qty = qty;
           var price = _context.ProductsInventorys.Find(id).UnitPrice;

            ViewBag.unitPrice = price;
            ViewBag.Total = qty * price;

           

            ViewBag.dum = id;

            return View();
        
        }

        [HttpPost]
        public IActionResult Create(Sales model)
        {

            
            

            if (ModelState.IsValid)
            {
                Sales newSal = new Sales
                {
                    EmpId = model.EmpId,
                    CustOrderId = model.CustOrderId,
                    Total = model.Total,
                    Paid = model.Paid,
                    Due = model.Due,
                    DeliveryDate = model.DeliveryDate
                };
                _salesRepository.Add(newSal);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Sales sal = _salesRepository.GetSales(id);
            Sales salObj = new Sales
            {
                SaleId = sal.SaleId,
                EmpId = sal.EmpId,
                CustOrderId = sal.CustOrderId,
                Total = sal.Total,
                Paid = sal.Paid,
                Due = sal.Due,
                DeliveryDate = sal.DeliveryDate
            };
            return View(salObj);
        }

        [HttpPost]
        public IActionResult Edit(Sales model)
        {
            if (ModelState.IsValid)
            {
                Sales sel = _salesRepository.GetSales(model.SaleId);
                sel.EmpId = model.EmpId;
                sel.CustOrderId = model.CustOrderId;
                sel.Total = model.Total;
                sel.Paid = model.Paid;
                sel.Due = model.Due;
                sel.DeliveryDate = model.DeliveryDate;

                Sales updateProductInventory = _salesRepository.Update(sel);
                return RedirectToAction("Index");
            }
            return View(model);
        }

    }
}

FactoryMM/Controllers/SupplierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FactoryMM.Models.SupplierMm;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FactoryMM.Controllers
{
    public class SupplierController : Controller
    {
        private ISupplierRepository _supplierRepository;

        public SupplierController(ISupplierRepository supplierRepository)
        {
            _supplierRepository = supplierRepository;
        }

        public IActionResult Index()
        {
            var model = _supplierRepository.GetAllSupplier();
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Supplier model)
        {
            if (ModelState.IsValid)
            {
                Supplier newSup = new Supplier
                {
                    SupName = model.SupName,
                    Phone = model.Phone,
                    Email = model.Email,
                    OrgName = model.OrgName,
                    Address = model.Address
                };
                _supplierRepository.Add(newSup);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Supplier cstomer = _supplierRepository.GetSupplier(id);
            Supplier cstomerObj = new Supplier
            {
                SupId = cstomer.SupId,
                SupName = cstomer.SupName,
                Phone = cstomer.Phone,
                Email = cstomer.Email,
                OrgName = cstomer.OrgName,
                Address = cstomer.Address
            };
            return View(cstomerObj);
        }

        [HttpPost]
        public IActionResult Edit(Supplier model)
        {
            if (ModelState.IsValid)
            {
                Supplier sup = _supplierRepository.GetSupplier(model.SupId);
                sup.SupName = model.SupName;
                sup.Phone = model.Phone;
                sup.Email = model.Email;
                sup.OrgName = model.OrgName;
                sup.Address = model.Address;

                Supplier updateProductInventory = _supplierRepository.Update(sup);
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

FactoryMM/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "Not Found";
}

<h1>@ViewBag.ErrorMessage</h1>


<a asp-action="Index" asp-controller="Home">
    Click here to navigate to the home page
</a>

FactoryMM/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signInManager;

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <environment include="Development">
        <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/jquery-validate/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.js"></script>
        <script src="~/AditionalDesign/jquery/jquery-3.2.1.min.js"></script>
        <script src="~/AditionalDesign/animsition/js/animsition.min.js"></script>
        <script src="~/AditionalDesign/bootstrap/js/popper.js"></script>



        <!--Design-->
        <link href="~/AditionalDesign/css/new.css" rel="stylesheet" />

        <!-- Bootstrap CSS File -->
        <link href="~/Content/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">

        <!-- Libraries CSS Files -->
        <link href="~/AditionalDesign/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
        <link href="~/AditionalDesign/lib/animate/animate.min.css" rel="stylesheet">
        <link href="~/AditionalDesign/lib/ionicons/css/ionicons.min.css" rel="stylesheet">
        <link href="~/AditionalDesign/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
        <link href="~/AditionalDesign/lib/lightbox/css/lightbox.min.css" rel="stylesheet">
        <link href="~/AditionalDesign/animate/animate.css">
        <link href="~/AditionalDesign/css-hamburgers/hamburgers.min.css">
        <link href="~/AditionalDesign/animsition/css/animsition.min.css">
        <link href="~/AditionalDesign/select2/select2.min.css">
        <link href="~/AditionalDesign/select2/select2.min.css">
        <link href="~/AditionalDesign/noui/nouislider.min.css">

        <!-- Main Stylesheet File -->
        <link href="~/css/new.css" rel="stylesheet" />
        <link href="~/css/style.css" rel="stylesheet" /> <link href="~/css/style.css" rel="stylesheet" />
                                                         <link href="~/css/new.css" rel="stylesheet" />
        <link href="~/css/main.css" rel="stylesheet" /> <!--Design-->


    </environment>
    <environment exclude="Development">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
              crossorigin="anonymous"
              asp-fallback-href="~/lib/bootstrap/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position"
              asp-fallback-test-value="absolute"
              asp-supperss-fallback-integrity="true">

        <!--Design-->
        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">
        <!-- Bootstrap CSS File -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
        <!--Design-->
    </environment>
    <link href="~/css/new.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />

    <link href="~/css/site.css" rel="stylesheet" />

    <title>@ViewBag.Title</title>
</head>
<body>

    <div class="container-fluid">
        <header id="header" class="fixed-top">
            <div class="container-fluid">

                <div class="logo float-left">
                    <a asp-controller="Home" asp-action="Index" class="scrollto"><img src="~/images/Additional/logo.png"  width="110" height="80" style="padding-top:15px;" alt="" class="img-fluid"></a>
                </div>


                <nav id="bt_hover" class="main-nav  d-none d-lg-block" style="position:center;">
                    <ul>
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                        <li class="drop-down">
                            <a>Our Company</a>
                            <ul>
                                <li><a href="#about">About Us</a></li>
                                <li><a href="#portfolio">Raw Materials</a></li>
                                <li><a href="#clients">Our Products</a></li>
                                <li><a href="#team">Board of Management</a></li>
                            </ul>
                        </li>
                        <li class="drop-down">
                            <a >Sales</a>
                            <ul>
                                <li><a asp-controller="CustOrder" asp-action="Index">Customer Order</a></li>
                                <li><a asp-controller="Sales" asp-action="Index">Sale Products</a></li>
                                <li><a asp-controller="SalesReturns" asp-action="Index">Products Return</a></li>
                            </ul>
                        </li>
                        <li class="drop-down">
                            <a >Purchase</a>
                            <ul>
                                <li><a href="#">Place Order</a></li>
                                <li><a href="#">Purchase Materials</a></li>
                            </ul>
                        </li>
                        <li class="drop-down">
                            <a >Inventory</a>
                            <ul>
                                <li><a asp-controller="ProductInventorys" asp-action="Index">Product Inventory</a></li>
                                <li><a asp-controller="MaterialInventorys" asp-action="Index">Material Inventory</a></li>
                            </ul>
                        </li>
                        <li><a asp-controller="Productions" asp-action="Index">Production</a></li>
                        <li class="drop-down">
                            <a >Account Sectio</a>
                            <ul>
                                <li><a href="#">......</a></li>
                                <li><a href="#">......</a></li>
                            </ul>
                        </li>
                        <li class="drop-down">
                            <a>Others</a>
                            <ul>
                                <li> <a asp-controller="Customers" asp-action="index">Custommers List</a></li>
                                <li> <a asp-controller="Supplier" asp-action="index">Supplier List</a></li>
                                <li> <a asp-controller="Employees" asp-action="index">Employee List</a></li>
                                <li> <a asp-controller="SalesReturns" asp-action="index">Sales Return List</a></li>
                                <li> <a asp-controller="Sales" asp-action="index">Sales List</a></li>
                                <li> <a asp-controller="Administration" asp-action="ListRoles">ListRoles</a></li>
                             
                            </ul>
                        </li>
                        <li><a href="#contact">Contact Us</a></li>

                        
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <form method="post" asp-action="Logout" asp-controller="Account">
                                    <button type="submit" class="nav-link btn btn-link py-0" style="width:auto;">
                                        Logout @User.Identity.Name
                                    </button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li style=" color:#ffffff; background-color:#ff0000; "><a asp-controller="Account" asp-action="Register">Register</a></li>
                            <li style="background-color:#0094ff; color:#ffffff;"><a asp-controller="Account" asp-action="Login">Login</a></li>
                        }
                    </ul>
                </nav><!-- .main-nav -->


            </div>
        </header>

        <div>
            @RenderBody()
        </div>

        <footer id="footer">
            <div class="footer-top">
                <div class="container">
                    <div class="row">

                        <div class="col-lg-4 col-md-6 footer-info">
                            <h3>NORTH BENGAL</h3>
                            <p>NORTH BENGAL Group is committed to complying with all applicable laws wherever we operate in order to meet our obligations to detect, prevent and eliminate, as well as reduce opportunities for bribery and corruption.</p>
                        </div>

                        <div class="col-lg-2 col-md-6 footer-links">
                            <h4>Useful Links</h4>
                            <ul>
                                <li><a href="#">Home</a></li>
                                <li><a href="#">About us</a></li>
                                <li><a href="#">Our Products</a></li>
                                <li><a href="#">Raw Materials</a></li>
                            </ul>
                        </div>

                        <div class="col-lg-3 col-md-6 footer-contact">
                            <h4>Contact Us</h4>
                            <p>
                                Nazrul islam Road, West Palsha <br>
                                Charmatha, Bogra 5800<br>
                                Bangladesh <br>
                                <strong>Phone:</strong> 01717954232<br>
                                <strong>Email:</strong> nazmussakib95@gmail.com<br>
                            </p>

                        </div>


                    </div>
                </div>
            </div>

            <div class="container">
                <div class="copyright">
                    &copy; Copyright <strong>FARHAN ISHRAQ SHANTO</strong>. All Rights Reserved
                </div>
                <div class="credits">
                    <!--
                      All the links in the footer should remain intact.
                      You can delete the links only if you purchased the pro version.
                      Licensing information: https://bootstrapmade.com/license/
                      Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=NewBiz
                    -->
                    Designed by <a href="https://www.facebook.com/farhan.shanto" style="color:yellow">Shanto</a>
                </div>
            </div>
            @*<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>*@
        </footer>

        @if (IsSectionDefined("Scripts"))
        {
            @RenderSection("Scripts", required: false)
        }
    </div>
</body>
</html>