FactoryMM/Controllers/CustOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Providers.Entities;
using FactoryMM.Data;
using FactoryMM.Models.CustomersOrderMm;
using FactoryMM.Models.CustommerMm;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FactoryMM.Controllers
{
    public class CustOrderController : Controller
    {
        private ICustomerOrderRepository _customerOrderRepository;
        private AppDbContext _contex;

        public CustOrderController(ICustomerOrderRepository customerOrderRepository, AppDbContext contex)
        {
            _customerOrderRepository = customerOrderRepository;
            _contex = contex;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            var model = _customerOrderRepository.GetAllCustomerOrder();
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            List<Customer> custNames = new List<Customer>();

            custNames = _contex.Customers.ToList();
            custNames.Insert(0, new Customer { CustId = 0, CustName = "Select" });
            ViewBag.Customer = custNames;
            return View();
        }

        [HttpPost]
        public IActionResult Create(CustomerOrder model)
        {
            if (ModelState.IsValid)
            {
                CustomerOrder newCustomerOrder = new CustomerOrder
                {
                    CustId = model.CustId,
                    ProdInvId = model.ProdInvId,
                    Quantity = model.Quantity,
                    OrderDate = model.OrderDate,
                    DeliveryTakeDate = model.DeliveryTakeDate
                };

                HttpContext.Session.SetString("Test", model.Quantity.ToString());
                _customerOrderRepository.Add(newCustomerOrder);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            CustomerOrder cstomer = _customerOrderRepository.GetCustomerOrder(id);
            CustomerOrder cstomerObj = new CustomerOrder
            {
                CustOrderId = cstomer.CustOrderId,
                CustId = cstomer.CustId,
                ProdInvId = cstomer.ProdInvId,
                Quantity = cstomer.Quantity,
                OrderDate = cstomer.OrderDate,
                DeliveryTakeDate = cstomer.DeliveryTakeDate
            };
            return View(cstomerObj);
        }

        [HttpPost]
        public IActionResult Edit(CustomerOrder model)
        {
            if (ModelState.IsValid)
            {
                CustomerOrder cstomerOrder = _customerOrderRepository.GetCustomerOrder(model.CustOrderId);
                cstomerOrder.CustId = model.CustId;
                cstomerOrder.ProdInvId = model.ProdInvId;
                cstomerOrder.Quantity = model.Quantity;
                cstomerOrder.OrderDate = model.OrderDate;
                cstomerOrder.DeliveryTakeDate = model.DeliveryTakeDate;

                CustomerOrder updateProductInventory = _customerOrderRepository.Update(cstomerOrder);
                return RedirectToAction("Index");
            }
            return View(model);
        }

    }
}

FactoryMM/Controllers/ProductInventorysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FactoryMM.Models.InventoryMm.ProductInventoryMm;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FactoryMM.Controllers
{
    public class ProductInventorysController : Controller
    {
        private IProductInventoryRepository _productInventoryRepository;

        public ProductInventorysController(IProductInventoryRepository productInventoryRepository)
        {
            _productInventoryRepository = productInventoryRepository;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            var model = _productInventoryRepository.GetAllProductInventory();
            return View(model);
        }

         

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(ProductInventory model)
        {
            if(ModelState.IsValid)
            {
                ProductInventory newProductInventory = new ProductInventory
                {
                    ProdInvName = model.ProdInvName,
                    Description = model.Description,
                    Quantity = model.Quantity,
                    UnitPrice = model.UnitPrice
                };
                _productInventoryRepository.Add(newProductInventory);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ProductInventory productInventory = _productInventoryRepository.GetProductInventory(id);
            ProductInventory productInventoryObj = new ProductInventory
            {
                ProdInvId = productInventory.ProdInvId,
                ProdInvName = productInventory.ProdInvName,
                Description = productInventory.Description,
                Quantity = productInventory.Quantity,
                UnitPrice = productInventory.UnitPrice
            };
            return View(productInventoryObj);
        }

        [HttpPost]
        public IActionResult Edit(ProductInventory model)
        {
            if (ModelState.IsValid)
            {
                ProductInventory productInventory = _productInventoryRepository.GetProductInventory(model.ProdInvId);
                productInventory.ProdInvName = model.ProdInvName;
                productInventory.Description = model.Description;
                productInventory.Quantity = model.Quantity;
                productInventory.UnitPrice = model.UnitPrice;

                ProductInventory updateProductInventory = _productInventoryRepository.Update(productInventory);
                return RedirectToAction("Index");
            }
            return View(model);
        }

    }
}

FactoryMM/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FactoryMM.Data;
using FactoryMM.Models.CustomersOrderMm;
using FactoryMM.Models.SalesMm;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FactoryMM.Controllers
{
    public class SalesController : Controller
    {
        private AppDbContext _context;
        private ISalesRepository _salesRepository;
        private ICustomerOrderRepository _customerOrderRepository;

        public SalesController(ISalesRepository salesRepository, ICustomerOrderRepository customerOrderRepository,AppDbContext context)
        {
            _context = context;
            _salesRepository = salesRepository;
            _customerOrderRepository = customerOrderRepository;


        }

        public IActionResult Index()
        {
            var model = _salesRepository.GetAllSales();
            return View(model);
        }

        [HttpGet]
        public IActionResult Create(int id)
        {
            var qty = _context.CustomerOrders.Find(id).Quantity;
            ViewBag.qty = qty;
           var price = _context.ProductsInventorys.Find(id).UnitPrice;

            ViewBag.unitPrice = price;
            ViewBag.Total = qty * price;

           

            ViewBag.dum = id;

            return View();
        
        }

        [HttpPost]
        public IActionResult Create(Sales model)
        {

            
            

            if (ModelState.IsValid)
            {
                Sales newSal = new Sales
                {
                    EmpId = model.EmpId,
                    CustOrderId = model.CustOrderId,
                    Total = model.Total,
                    Paid = model.Paid,
                    Due = model.Due,
                    DeliveryDate = model.DeliveryDate
                };
                _salesRepository.Add(newSal);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Sales sal = _salesRepository.GetSales(id);
            Sales salObj = new Sales
            {
                SaleId = sal.SaleId,
                EmpId = sal.EmpId,
                CustOrderId = sal.CustOrderId,
                Total = sal.Total,
                Paid = sal.Paid,
                Due = sal.Due,
                DeliveryDate = sal.DeliveryDate
            };
            return View(salObj);
        }

        [HttpPost]
        public IActionResult Edit(Sales model)
        {
            if (ModelState.IsValid)
            {
                Sales sel = _salesRepository.GetSales(model.SaleId);
                sel.EmpId = model.EmpId;
                sel.CustOrderId = model.CustOrderId;
                sel.Total = model.Total;
                sel.Paid = model.Paid;
                sel.Due = model.Due;
                sel.DeliveryDate = model.DeliveryDate;

                Sales updateProductInventory = _salesRepository.Update(sel);
                return RedirectToAction("Index");
            }
            return View(model);
        }

    }
}

FactoryMM/Views/CustOrder/Create.cshtml
@model CustomerOrder



@{
    ViewData["Title"] = "Create";
}

<style>
    .width30 {
        width: 30%;
    }

    .width70 {
        width: 70%;
    }

    .floatL {
        float: left;
    }

    .width50 {
        width: 50%;
    }

    .floatR {
        float: right;
    }

    .btn {
        width: 100%;
        border-radius: 0px;
    }

    .width100 {
        width: 100%;
    }

    .row {
        margin-left: -20px;
        margin-right: -20px;
    }

    .boxStyle {
        padding: 20px;
        border-radius: 25px;
        border-top: 6px solid #dc3545;
        border-bottom: 6px solid #28a745;
    }
</style>
<body class="bg-dark">
    <header class="bg-dark" style="height: 60px; padding: 5px;">
        <h3 class="text-light" style="text-align: center;">Create Customer Order</h3>
    </header>
    <div class="container bg-dark">
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-sm-2"></div>
            <div class="col-sm-6 bg-light boxStyle">
                <form  asp-controller="CustOrder" asp-action="Create" method="post" class="mt-3">
                    <div class="form-group">
                        <div class="width30 floatL"><label>Customrer Name</label></div>
                        
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                        
                        <select asp-for="CustId"
                                class="form-control"
                                asp-items="@(new SelectList(@ViewBag.Customer,"CustId", "CustName"))">
                        </select>
                    </div>
                        <br><br>
                        <div class="form-group">
                            <div class="width30 floatL"><label>Product Name</label></div>
                            <div class="width70 floatR">
                                <select asp-for="ProdInvId" class="custom-select mr-sm-2"
                                        asp-items="Html.GetEnumSelectList<ProdName>()">
                                    <option value="">Please Select</option>
                                </select>
                                @*<input asp-for="ProdInvId" class="width100 form-control" name="ProdInvId" type="text" value="" size="20">
        <span asp-validation-for="ProdInvId" class="text-danger"></span>*@
                            </div>
                        </div><br>
                        <div class="form-group">
                            <div class="width30 floatL"><label>Quantity</label></div>
                            <div class="width70 floatR">
                                <input asp-for="Quantity" class="width100 form-control" name="Quantity" src="" type="text" value="" size="20">
                                <span asp-validation-for="Quantity" class="text-danger"></span>
                            </div>
                        </div><br>
                        <div class="form-group">
                            <div class="width30 floatL"><label>OrderDate</label></div>
                            <div class="width70 floatR">
                                <input asp-for="OrderDate" class="width100 form-control" name="OrderDate"   value="@DateTime.Now" size="20">
                                <span asp-validation-for="OrderDate" class="text-danger"></span>
                            </div>
                        </div><br>
                        <div class="form-group">
                            <div class="width30 floatL"><label>DeliveryTakeDate</label></div>
                            <div class="width70 floatR">
                                <input asp-for="DeliveryTakeDate" class="width100 form-control" name="address" type="text" value="" size="20">
                                <span asp-validation-for="DeliveryTakeDate" class="text-danger"></span>
                            </div>
                        </div><br><br><br>

                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div style="padding-left:80px;" class="form-group row ">
                            <div class="btn-group btn-group-justified col-sm-10">
                                <button type="submit" class="btn btn-primary">Create</button>
                                <a asp-controller="CustOrder" asp-action="Index" class="btn btn-danger">Cancel</a>
                            </div>
                        </div>

                       

                    </div>
                </form>
            </div>
            
        </div>
    </div>

</body>


@*<form asp-controller="CustOrder" asp-action="Create" method="post" class="mt-3">
        <div class="form-group row">
            <label asp-for="CustId" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="CustId" class="form-control" placeholder="CustId" />
                <span asp-validation-for="CustId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="ProdInvId" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="ProdInvId" class="form-control" placeholder="ProdInvId" />
                <span asp-validation-for="ProdInvId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Quantity" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Quantity" class="form-control" placeholder="Quantity" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="OrderDate" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="OrderDate" class="form-control" placeholder="OrderDate" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="DeliveryTakeDate" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="DeliveryTakeDate" class="form-control" placeholder="DeliveryTakeDate" />
                <span asp-validation-for="DeliveryTakeDate" class="text-danger"></span>
            </div>
        </div>


        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Create</button>
                <a asp-controller="CustOrder" asp-action="Index" class="btn btn-primary">Cancel</a>
            </div>
        </div>


    </form>*@

@*<div class="form-group row">
        <div class="col-sm-10">
            Total Employee Count = @_empRepository.GetAllEmployees().Count();
        </div>
    </div>*@


@*This script is required to display the selected file in the file upload element*@

FactoryMM/Views/CustOrder/Createsel.cshtml
@model Sales

@{
    ViewData["Title"] = "Edit";
}

<form asp-controller="Sales" asp-action="Edit" method="post" class="mt-3">

    <input hidden asp-for="SaleId" />

    <div class="form-group row">
        <label asp-for="EmpId" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="EmpId" class="form-control" placeholder="EmpId" />
            <span asp-validation-for="EmpId" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="CustOrderId" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="CustOrderId" class="form-control" placeholder="CustOrderId" />
            <span asp-validation-for="CustOrderId" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Total" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Total" class="form-control" placeholder="Total" />
            <span asp-validation-for="Total" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Paid" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Paid" class="form-control" placeholder="Paid" />
            <span asp-validation-for="Paid" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Due" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Due" class="form-control" placeholder="Due" />
            <span asp-validation-for="Due" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="DeliveryDate" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="DeliveryDate" class="form-control" placeholder="DeliveryDate" />
            <span asp-validation-for="DeliveryDate" class="text-danger"></span>
        </div>
    </div>


    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Create</button>
            <a asp-controller="Sales" asp-action="Index" class="btn btn-primary">Cancel</a>
        </div>
    </div>


</form>

FactoryMM/Views/CustOrder/Edit.cshtml
@model CustomerOrder

@{
    ViewData["Title"] = "Edit";
}

<form asp-controller="CustOrder" asp-action="Edit" method="post" class="mt-3">

    <input hidden asp-for="CustOrderId" />

    <div class="form-group row">
        <label asp-for="CustId" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="CustId" class="form-control" placeholder="CustId" />
            <span asp-validation-for="CustId" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="ProdInvId" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="ProdInvId" class="form-control" placeholder="ProdInvId" />
            <span asp-validation-for="ProdInvId" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Quantity" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Quantity" class="form-control" placeholder="Quantity" />
            <span asp-validation-for="Quantity" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="OrderDate" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="OrderDate" class="form-control" placeholder="OrgName" />
            <span asp-validation-for="OrderDate" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="DeliveryTakeDate" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="DeliveryTakeDate" class="form-control" placeholder="Address" />
            <span asp-validation-for="DeliveryTakeDate" class="text-danger"></span>
        </div>
    </div>


    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Create</button>
            <a asp-controller="CustoCustOrdermers" asp-action="Index" class="btn btn-primary">Cancel</a>
        </div>
    </div>



    @*<div class="form-group row">
            <div class="col-sm-10">
                Total Employee Count = @_empRepository.GetAllEmployees().Count();
            </div>
        </div>*@


    @*This script is required to display the selected file in the file upload element*@


</form>

FactoryMM/Views/CustOrder/Index.cshtml
@model IEnumerable<CustomerOrder>

@{
    ViewData["Title"] = "Index";
}

<div>
    <a asp-controller="CustOrder" asp-action="Create" type="button" class="btn btn-primary btn-lg btn-block m-2" style="width:300px;">Create New Employee </a>


    <table class="table table-striped table-dark">
        <thead>
            <tr>
                <th scope="col">CustOrderId</th>
                <th scope="col">CustId</th>
                <th scope="col">ProdInvId</th>
                <th scope="col">Quantity</th>
                <th scope="col">OrderDate</th>
                <th scope="col">DeliveryTakeDate</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var customer in Model)
            {
                <tr>
                    <th scope="row">@customer.CustOrderId</th>
                    <td>@customer.CustId</td>
                    <td>@customer.ProdInvId</td>
                    <td>@customer.Quantity</td>
                    <td>@customer.OrderDate</td>
                    <td>@customer.DeliveryTakeDate</td>
                    <td><a asp-controller="CustOrder" asp-action="Edit" asp-route-id="@customer.CustOrderId">Edit</a></td>
                    <td><a asp-controller="Sales" asp-action="Create" asp-route-id="@customer.CustOrderId">Sale</a></td>
                    <td>Cansel</td>

                </tr>
            }
        </tbody>
    </table>

</div>

FactoryMM/Views/CustOrder/Index1.cshtml
@*@model CustomerOrder
@{
    ViewData["Title"] = "Create";
}

<style>
    .width30 {
        width: 30%;
    }

    .width70 {
        width: 70%;
    }

    .floatL {
        float: left;
    }

    .width50 {
        width: 50%;
    }

    .floatR {
        float: right;
    }

    .btn {
        width: 100%;
        border-radius: 0px;
    }

    .width100 {
        width: 100%;
    }

    .row {
        margin-left: -20px;
        margin-right: -20px;
    }

    .boxStyle {
        padding: 20px;
        border-radius: 25px;
        border-top: 6px solid #dc3545;
        border-bottom: 6px solid #28a745;
    }
</style>
<body class="bg-dark">
    <header class="bg-dark" style="height: 60px; padding: 5px;">
        <h3 class="text-light" style="text-align: center;">Create Customer Order</h3>
    </header>
    <div class="container bg-dark">
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-sm-2"></div>
            <div class="col-sm-6 bg-light boxStyle">
                <form asp-controller="ProductInventorys" asp-action="Create" method="post" class="mt-3">
                    <div class="form-group">
                        <div class="width30 floatL"><label>ProdInvName Name</label></div>
                        <div class="width70 floatR">
                            <input asp-for="ProdInvName" id="CustId" class="width100 form-control" name="firstname" type="text" value="" size="20">
                            <span asp-validation-for="ProdInvName" class="text-danger"></span>
                        </div><br><br>
                        <div class="form-group">
                            <div class="width30 floatL"><label>Description Name</label></div>
                            <div class="width70 floatR">
                                <input asp-for="Description" class="width100 form-control" name="ProdInvId" type="text" value="" size="20">
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div><br><br>
                        <div class="form-group">
                            <div class="width30 floatL"><label>Quantity</label></div>
                            <div class="width70 floatR">
                                <input asp-for="Quantity" class="width100 form-control" name="Quantity" src="" type="text" value="" size="20">
                                <span asp-validation-for="Quantity" class="text-danger"></span>
                            </div>
                        </div><br><br>
                        <div class="form-group">
                            <div class="width30 floatL"><label>UnitPrice</label></div>
                            <div class="width70 floatR">
                                <input asp-for="UnitPrice" class="width100 form-control" name="OrderDate" type="text" value="" size="20">
                                <span asp-validation-for="UnitPrice" class="text-danger"></span>
                            </div>
                        </div><br><br><br>

                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div style="padding-left:80px;" class="form-group row ">
                            <div class="btn-group btn-group-justified col-sm-10">
                                <button type="submit" class="btn btn-primary">Create</button>
                                <a asp-controller="ProductInventorys" asp-action="Index" class="btn btn-danger">Cancel</a>
                            </div>
                        </div>



                    </div>
                </form>
            </div>

        </div>
    </div>

</body>*@