FactoryMM/Models/InventoryMm/MaterialInventoryMm/MaterialInventory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace FactoryMM.Models.InventoryMm.MaterialInventoryMm
{
    public class MaterialInventory
    {
        [Key]
        public int MatInvId { get; set; }

        [Required, MaxLength(50, ErrorMessage = "Name cannot exceed 50 characters")]
        public string MatInvName { get; set; }
        public string Description { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public decimal Quantity { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal UnitPrice { get; set; }
        public int SupId { get; set; }

    }
}

FactoryMM/Controllers/MaterialInventorysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FactoryMM.Models.InventoryMm.MaterialInventoryMm;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FactoryMM.Controllers
{
    public class MaterialInventorysController : Controller
    {
        private IMaterialInventoryRepository _materialInventoryRepository;

        public MaterialInventorysController(IMaterialInventoryRepository materialInventoryRepository)
        {
            _materialInventoryRepository = materialInventoryRepository;
        }
        

        // GET: /<controller>/
        public IActionResult Index()
        {
            var model = _materialInventoryRepository.GetAllMaterialInventory();
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(MaterialInventory model)
        {
            if(ModelState.IsValid)
            {
                MaterialInventory newMaterialInventory = new MaterialInventory
                {
                    MatInvName = model.MatInvName,
                    Description = model.Description,
                    Quantity = model.Quantity,
                    UnitPrice = model.UnitPrice,
                    SupId = model.SupId
                };
                _materialInventoryRepository.Add(newMaterialInventory);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            MaterialInventory materialInventory = _materialInventoryRepository.GetMaterialInventory(id);
            MaterialInventory materialInventoryObj = new MaterialInventory
            {
                MatInvId = materialInventory.MatInvId,
                MatInvName = materialInventory.MatInvName,
                Description = materialInventory.Description,
                Quantity = materialInventory.Quantity,
                UnitPrice = materialInventory.UnitPrice,
                SupId = materialInventory.SupId
            };
            return View(materialInventoryObj);
        }

        [HttpPost]
        public IActionResult Edit(MaterialInventory model)
        {
            if(ModelState.IsValid)
            {
                MaterialInventory materialInventory = _materialInventoryRepository.GetMaterialInventory(model.MatInvId);
                materialInventory.MatInvName = model.MatInvName;
                materialInventory.Description = model.Description;
                materialInventory.Quantity = model.Quantity;
                materialInventory.UnitPrice = model.UnitPrice;
                materialInventory.SupId = model.SupId;

                MaterialInventory updateMaterialInventory = _materialInventoryRepository.Update(materialInventory);
                return RedirectToAction("Index");
            }
            return View(model);
        }
        
    }
}

FactoryMM/Views/MaterialInventorys/Create.cshtml
@model MaterialInventory
@{
    ViewData["Title"] = "Create";
}

<form asp-controller="MaterialInventorys" asp-action="Create" method="post" class="mt-3">
    <div class="form-group row">
        <label asp-for="MatInvName" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="MatInvName" class="form-control" placeholder="MatInvName" />
            <span asp-validation-for="MatInvName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Description" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Description" class="form-control" placeholder="Description" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Quantity" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Quantity" class="form-control" placeholder="Quantity" />
            <span asp-validation-for="Quantity" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="UnitPrice" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="UnitPrice" class="form-control" placeholder="UnitPrice" />
            <span asp-validation-for="UnitPrice" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="SupId" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="SupId" class="form-control" placeholder="Paid" />
            <span asp-validation-for="SupId" class="text-danger"></span>
        </div>
    </div>
    

    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Create</button>
            <a asp-controller="MaterialInventorys" asp-action="Index" class="btn btn-primary">Cancel</a>
        </div>
    </div>



    @*<div class="form-group row">
            <div class="col-sm-10">
                Total Employee Count = @_empRepository.GetAllEmployees().Count();
            </div>
        </div>*@


    @*This script is required to display the selected file in the file upload element*@


</form>

FactoryMM/Views/MaterialInventorys/Edit.cshtml
@model MaterialInventory

@{
    ViewData["Title"] = "Edit";
}

<form asp-controller="MaterialInventorys" asp-action="Edit" method="post" class="mt-3">

    <input hidden asp-for="MatInvId" />

    <div class="form-group row">
        <label asp-for="MatInvName" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="MatInvName" class="form-control" placeholder="MatInvName" />
            <span asp-validation-for="MatInvName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Description" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Description" class="form-control" placeholder="Description" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Quantity" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Quantity" class="form-control" placeholder="Quantity" />
            <span asp-validation-for="Quantity" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="UnitPrice" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="UnitPrice" class="form-control" placeholder="Paid" />
            <span asp-validation-for="UnitPrice" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="SupId" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="SupId" class="form-control" placeholder="SupId" value="@DateTime.Now" />
            <span asp-validation-for="SupId" class="text-danger"></span>
        </div>
    </div>

    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Create</button>
            <a asp-controller="MaterialInventorys" asp-action="Index" class="btn btn-primary">Cancel</a>
        </div>
    </div>



    @*<div class="form-group row">
            <div class="col-sm-10">
                Total Employee Count = @_empRepository.GetAllEmployees().Count();
            </div>
        </div>*@


    @*This script is required to display the selected file in the file upload element*@


</form>

FactoryMM/Views/MaterialInventorys/Index.cshtml
@model IEnumerable<MaterialInventory>

@{
    ViewData["Title"] = "Index";
}

  
    <div>
        <a asp-controller="MaterialInventorys" asp-action="Create" type="button" class="btn btn-primary btn-lg btn-block m-2" style="width:300px;">Create New MaterialInventory </a>

        <table class="table table-striped table-dark">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">MatInvName</th>
                    <th scope="col">Description</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">UnitPrice</th>
                    <th scope="col">SupId</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var companyper in Model)
                {
                    <tr>
                        <th scope="row">@companyper.MatInvId</th>
                        <td>@companyper.MatInvName</td>
                        <td>@companyper.Description</td>
                        <td>@companyper.Quantity</td>
                        <td>@companyper.UnitPrice</td>
                        <td>@companyper.SupId</td>

                        <td><a asp-controller="MaterialInventorys" asp-action="Edit" asp-route-id="@companyper.MatInvId">Edit</a></td>
                        <td>Delete</td>

                    </tr>
                }
            </tbody>
        </table>

    </div>