FactoryMM/Models/SalesMm/SalesReturnMm/SalesReturn.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace FactoryMM.Models.SalesMm.SalesReturnMm
{
    public class SalesReturn
    {
        [Key]
        public int SaleReturnId { get; set; }
        public int ProdInvId { get; set; }
        public int CustId { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal Quantity { get; set; }

        public DateTime ErturnDate { get; set; }
    }
}

FactoryMM/Controllers/SalesReturnsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FactoryMM.Models.ReturnSels;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FactoryMM.Controllers
{
    public class SalesReturnsController : Controller
    {
        private IReturnSelseRepository _salesReturnRepository;

        public SalesReturnsController(IReturnSelseRepository salesReturnRepository)
        {
            _salesReturnRepository = salesReturnRepository;
        }

        public IActionResult Index()
        {
            var model = _salesReturnRepository.GetAllReturnSelse();
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(ReturnSelse model)
        {
            if (ModelState.IsValid)
            {
                ReturnSelse newSalRet = new ReturnSelse
                {
                    ProdInvId = model.ProdInvId,
                    CustId = model.CustId,
                    Quantity = model.Quantity,
                    ErturnDate = model.ErturnDate
                };
                _salesReturnRepository.Add(newSalRet);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ReturnSelse saleRet = _salesReturnRepository.GetReturnSelse(id);
            ReturnSelse saleRetObj = new ReturnSelse
            {
                SaleReturnId = saleRet.SaleReturnId,
                ProdInvId = saleRet.ProdInvId,
                CustId = saleRet.CustId,
                Quantity = saleRet.Quantity,
                ErturnDate = saleRet.ErturnDate
            };
            return View(saleRetObj);
        }

        [HttpPost]
        public IActionResult Edit(ReturnSelse model)
        {
            if (ModelState.IsValid)
            {
                ReturnSelse selRet = _salesReturnRepository.GetReturnSelse(model.SaleReturnId);
                
                selRet.ProdInvId = model.ProdInvId;
                selRet.CustId = model.CustId;
                selRet.Quantity = model.Quantity;
                selRet.ErturnDate = model.ErturnDate;

                ReturnSelse updateProductInventory = _salesReturnRepository.Update(selRet);
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

FactoryMM/Views/SalesReturns/Create.cshtml
@model ReturnSelse
@{
    ViewData["Title"] = "Create";
}


<style>
    .width30 {
        width: 30%;
    }

    .width70 {
        width: 70%;
    }

    .floatL {
        float: left;
    }

    .width50 {
        width: 50%;
    }

    .floatR {
        float: right;
    }

    .btn {
        width: 100%;
        border-radius: 0px;
    }

    .width100 {
        width: 100%;
    }

    .row {
        margin-left: -20px;
        margin-right: -20px;
    }

    .boxStyle {
        padding: 20px;
        border-radius: 25px;
        border-top: 6px solid #dc3545;
        border-bottom: 6px solid #28a745;
    }
</style>
<body class="bg-dark">
    <header class="bg-dark" style="height: 60px; padding: 5px;">
        <h3 class="text-light" style="text-align: center;">Create Customer Order</h3>
    </header>
    <div class="container bg-dark">
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-sm-2"></div>
            <div class="col-sm-6 bg-light boxStyle">
                <form asp-controller="SalesReturns" asp-action="Create" method="post" class="mt-3">
                    <div class="form-group">
                        <div class="width30 floatL"><label>ProdInvId Name</label></div>
                        <div class="width70 floatR">
                            <input asp-for="ProdInvId" id="CustId" class="width100 form-control" name="firstname" type="text" value="" size="20">
                            <span asp-validation-for="ProdInvId" class="text-danger"></span>
                        </div><br><br>
                        <div class="form-group">
                            <div class="width30 floatL"><label>CustId Name</label></div>
                            <div class="width70 floatR">
                                <input asp-for="CustId" class="width100 form-control" name="ProdInvId" type="text" value="" size="20">
                                <span asp-validation-for="CustId" class="text-danger"></span>
                            </div>
                        </div><br><br>
                        <div class="form-group">
                            <div class="width30 floatL"><label>Quantity</label></div>
                            <div class="width70 floatR">
                                <input asp-for="Quantity" class="width100 form-control" name="Quantity" src="" type="text" value="" size="20">
                                <span asp-validation-for="Quantity" class="text-danger"></span>
                            </div>
                        </div><br><br>
                        <div class="form-group">
                            <div class="width30 floatL"><label>ErturnDate</label></div>
                            <div class="width70 floatR">
                                <input asp-for="ErturnDate" class="width100 form-control" name="OrderDate" type="text" value="" size="20">
                                <span asp-validation-for="ErturnDate" class="text-danger"></span>
                            </div>
                        </div><br><br><br>

                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div style="padding-left:80px;" class="form-group row ">
                            <div class="btn-group btn-group-justified col-sm-10">
                                <button type="submit" class="btn btn-primary">Create</button>
                                <a asp-controller="SalesReturns" asp-action="Index" class="btn btn-danger">Cancel</a>
                            </div>
                        </div>



                    </div>
                </form>
            </div>

        </div>
    </div>

</body>

@*<form asp-controller="SalesReturns" asp-action="Create" method="post" class="mt-3">
        <div class="form-group row">
            <label asp-for="ProdInvId" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="ProdInvId" class="form-control" placeholder="ProdInvId" />
                <span asp-validation-for="ProdInvId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="CustId" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="CustId" class="form-control" placeholder="CustId" />
                <span asp-validation-for="CustId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Quantity" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Quantity" class="form-control" placeholder="Quantity" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="ErturnDate" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="ErturnDate" class="form-control" placeholder="ErturnDate" />
                <span asp-validation-for="ErturnDate" class="text-danger"></span>
            </div>
        </div>



        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Create</button>
                <a asp-controller="SalesReturns" asp-action="Index" class="btn btn-primary">Cancel</a>
            </div>
        </div>



    </form>*@

FactoryMM/Views/SalesReturns/Edit.cshtml
@model ReturnSelse

@{
    ViewData["Title"] = "Edit";
}

<form asp-controller="SalesReturns" asp-action="Edit" method="post" class="mt-3">

    <input hidden asp-for="SaleReturnId" />

    <div class="form-group row">
        <label asp-for="ProdInvId" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="ProdInvId" class="form-control" placeholder="ProdInvId" />
            <span asp-validation-for="ProdInvId" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="CustId" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="CustId" class="form-control" placeholder="CustId" />
            <span asp-validation-for="CustId" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Quantity" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Quantity" class="form-control" placeholder="Quantity" />
            <span asp-validation-for="Quantity" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="ErturnDate" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="ErturnDate" class="form-control" placeholder="ErturnDate" />
            <span asp-validation-for="ErturnDate" class="text-danger"></span>
        </div>
    </div>
 

    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Create</button>
            <a asp-controller="SalesReturns" asp-action="Index" class="btn btn-primary">Cancel</a>
        </div>
    </div>


</form>

FactoryMM/Views/SalesReturns/Index.cshtml
@model IEnumerable<ReturnSelse>

@{
    ViewData["Title"] = "Index";
}

<div>
    <a asp-controller="SalesReturns" asp-action="Create" type="button" class="btn btn-primary btn-lg btn-block m-2" style="width:300px;">Create New Return Sales </a>

    <table class="table table-striped table-dark">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">ProdInvId</th>
                <th scope="col">CustId</th>
                <th scope="col">Quantity</th>
                <th scope="col">ErturnDate</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var spret in Model)
            {
                <tr>
                    <th scope="row">@spret.SaleReturnId</th>
                    <td>@spret.ProdInvId</td>
                    <td>@spret.CustId</td>
                    <td>@spret.Quantity</td>
                    <td>@spret.ErturnDate</td>

                    <td><a asp-controller="SalesReturns" asp-action="Edit" asp-route-id="@spret.SaleReturnId">Edit</a></td>
                    <td>Delete</td>

                </tr>
            }
        </tbody>
    </table>

</div>